name: json2yaml
description: A new Flutter package project.
version: 0.0.1
author: Alexei Sintotski <alexei.sintotski@gmail.com>
homepage: https://github.com/alexei-sintotski/json2yaml

environment:
  sdk: ">=2.5.0 <3.0.0"
